
POST https://{{host}}/webhooks
Content-Type: {{contentType}}
aeg-event-type: Notification

[
  {
    "topic": "/subscriptions/1234/resourceGroups/test-rs-gp/providers/Microsoft.EventGrid/topics/test-eg-topic",
    "subject": "Group.Employee",
    "id": "ab8d8ef9-b929-46d8-b205-d72113750da1",
    "eventType": "Group.Employee",
    "eventTime": "2019-04-28T18:51:17.7994409Z",
    "data":{
    	"Id": "12345",
    	"FullName": "hello"
    },
    "dataVersion": "2",
    "metadataVersion": "1"
  }
]
